name: Build and Deploy README

on:
  workflow_dispatch:

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      - name: Create dist directory
        run: mkdir dist

      - name: Copy root assets to dist
        run: cp -r ./doc ./dist

      - name: Convert README.md to index.html
        run: pandoc README.md --template=.github/pages/templates.html -o dist/index.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: dist

  deploy:
    name: Deploy
    if: github.event_name != 'pull_request'
    needs: compile
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: pages
      cancel-in-progress: false
    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v3.0.6

      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v2.0.4