name: Build and Deploy README

on:
  workflow_dispatch:
  workflow_call:

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      - name: Create dist directory
        run: mkdir dist

      - name: Convert README.md to index.html
        run: pandoc README.md --template=.github/pages/templates.html -o dist/index.html